version: '3.8'
name: infra
services:
  api:
    image: ${DOCKER_REGISTRY-}appgroupfinancingapi
    build:
      context: .
      dockerfile: AppGroup.Financing.Api/Dockerfile
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  portainer:
    image: portainer/portainer-ce

volumes:
  portainer_data:
